---
- name: Hello World Playbook
  hosts: localhost
  connection: local  # No need for username and password with local connection
  gather_facts: true  # Skips fact collection since it's not needed

  tasks:
    - name: Finding the version of Targated node
      debug: 
        var: "Version:{{ ansible_distribution_version }}"


    - name: Print Hello World
      ansible.builtin.debug:
        msg: "Hello World"

# ---
# - name: Install and start nginx
