- name: nginx install and run
  hosts: frontend, local
  connection: local  # No need for username and password with local connection
  tasks:
  - name: install nginx server
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start nginx
    ansible.built.service:
      name: nginx
      state: started
      enable: yes